# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='url_link',
            new_name='url',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='site_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
