# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160109_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
