# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160109_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
