# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_articlecounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleCounts',
            new_name='ArticleCount',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 11, 21, 25, 16, 836757, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
