# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160111_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
