# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160112_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecount',
            name='article',
        ),
        migrations.AddField(
            model_name='articlecount',
            name='url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
