# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160112_0207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleCount',
        ),
    ]
