# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_articlecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
