# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20160114_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='real_pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 14, 22, 31, 47, 678133, tzinfo=utc), verbose_name='real pub date'),
            preserve_default=False,
        ),
    ]
