# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='images'),
        ),
    ]
