# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20160124_0306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleCount',
        ),
    ]
